/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://nffcl52n6bg4pbkoa2bxqxvq3i.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_wsEndpoint": "wss://nffcl52n6bg4pbkoa2bxqxvq3i.appsync-api.us-west-2.amazonaws.com/graphql", // WebSocket endpoint for subscriptions
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-k6d2szzsvjeqphzzzjz254zn3y",
    "aws_cognito_identity_pool_id": "us-west-2:7f79b999-d9d1-4712-9709-4cadfdcfd591",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_SWzbS7okQ",
    "aws_user_pools_web_client_id": "1cqj2ruvno68du2s0d6jui5re4",
    "oauth": {},
    "aws_cognito_username_attributes": ["EMAIL"],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": ["EMAIL"],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": ["SMS"],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": ["EMAIL"]
};

export default awsmobile;
